### ISSUE TITLE
Игра не отключает паузу после катсцены "Сражения с боссом"

### ISSUE THREAD

**Issue by SimplyTolex** [zziger/supercow-mod#10]
При появлении босса на экране игра покажет текст "Сражение с боссом!" и вместе с ним небольшую катсцену с приближением камеры на этого босса. Во время этого игра остановленна и ничего не происходит. После окончания катсцены игра возобновляется, однако, этого не происходит с установленным модом и включённым модулем `RENDER_UNFOCUSED`, что включён по умолчанию. Этот баг происходит с любым боссом.

#### Шаги для воспроизведения
- Открыть игру с модом
- подключить модуль `RENDER_UNFOCUSED` (всё остальное не важно)
- открыть уровень с любым боссом и дойти до него
- Супер Корова зависнет на месте, так же как и босс. Единственным выходом будет поставить игру на паузу и снять её с паузы.

#### Видео

https://user-images.githubusercontent.com/50412868/186636320-a50faaab-7812-4e46-becc-b9a3b9caef31.mp4

**Comment by zziger** [comment]
Исправлено в 2.0
