### ISSUE TITLE
команда help

### ISSUE THREAD

**Issue by SimplyTolex** [zziger/supercow-mod#13]
она будет показывать доступные команды

сейчас единственный способ их узнать - окрыть readme, которого у людей скорее всего не будет, а сама консоль ничего про команды не говорит

**Comment by SimplyTolex** [comment]
ну и еще при открытии консоли сразу писать сообщение типа "используйте команду help что бы узнать другие команды" (примерно так же как на некоторых линуксах пишет мол "используйте команду sudo что бы исполнять команды от лица суперпользователя..." или что то такое)

**Comment by zziger** [comment]
Системы команд больше нет в принципе
