### ISSUE TITLE
[идея] модуль, который выделяет монеты, которые ты не взял (и врагов, которых не убил и т.д.)

### ISSUE THREAD

**Issue by SimplyTolex** [zziger/supercow-mod#7]
Этот мод был бы очень неплох для практики в категории 99%

Работает примерно так: если ты проходишь уровень не на 100%, то открывается окно редактора (не картинками же), в котором монеты/сокровища/враги/секреты, которые ты пропустил, подсвечены. Теперь ты знаешь где они и тебе не нужно тратить 30м-2ч на их поиски.

Если есть какие-то вопросы то можете в комментариях тут спрашивать

**Comment by zziger** [comment]
Теперь это можно реализовать через скриптовое API
