### ISSUE TITLE
Адаптация для спидраннеров

### ISSUE THREAD

**Issue by zziger** [zziger/supercow-mod#9]
Нужно как-то помечать в игре, что загружены именно моды (не патчи), для того чтобы можно было легче модерировать спидраны

**Comment by SimplyTolex** [comment]
скорее нужно помечать не то что есть мод а что патч, а скорее, имеет ли изменение значимое влияние на игру или предоставляет нечестное преимущество

**Comment by zziger** [comment]
В спидранах SuperMod теперь запрещён
